import {ArrowLeft,ArrowUpRight,Bookmark,Bus,Car,Check,Clock3,Download,Leaf,MapPin,Printer,RefreshCw,Users} from 'lucide-react';
import type {Language,Plan} from '../types';
import {clock,money,tripDate} from '../types';
import {RouteMap} from './RouteMap';
import {t} from '../i18n';
export function Itinerary({plan,language,saved,onSave,onEdit,onDelay,onExport}:{plan:Plan;language:Language;saved:boolean;onSave:()=>void;onEdit:()=>void;onDelay:()=>void;onExport:()=>void}){
 return <><div className="page-intro itinerary-intro"><div><button className="text-button" onClick={onEdit}><ArrowLeft size={14}/>Back to your preferences</button><h1>Your day, thoughtfully arranged.</h1><p>Meaningful stops. A comfortable pace. Room for the unexpected.</p></div><button className={`button ${saved?'secondary':'primary'}`} onClick={onSave}>{saved?<Check size={16}/>:<Bookmark size={16}/>} {saved?'Saved in this browser':t(language).save}</button></div>
 <div className="journey-summary"><span><CalendarLabel date={plan.request.date}/></span><span><MapPin size={15}/> Madurai</span><span><Users size={15}/>{plan.request.party_size} travelers</span><span><Leaf size={15}/>{plan.request.pace==='relaxed'?'Unhurried pace':'Standard pace'}</span></div>
 <div className="journey-layout"><section><div className="timeline-head"><span className="eyebrow">YOUR ITINERARY</span><span className="muted-chip">{plan.stops.length} meaningful visits</span></div><div className="start-point"><div className="start-icon"><MapPin size={17}/></div><div><b>{plan.request.start_time} · Madurai Junction</b><p>Your journey begins here.</p></div></div>
 <div className="timeline">{plan.stops.map((stop,i)=><article className="timeline-stop" key={stop.place_id}><div className="timeline-number">{i+1}</div><div className="travel-line">{stop.mode==='cab'?<Car size={14}/>:<Bus size={14}/>} {stop.travel_minutes} min by {stop.mode}<span>· {money(stop.cost_inr)} for your group</span>{stop.wait_minutes>0&&<small> + {stop.wait_minutes} min before the opening session</small>}</div><div className="card stop-card"><div className="stop-top"><div><span className="eyebrow">{clock(stop.arrival_min)} – {clock(stop.departure_min)}</span><h2>{language==='ta'?stop.tamil_name:stop.name}</h2></div><span className="visit-badge">{plan.request.required_place_ids.includes(stop.place_id)?'A must-see':'A little extra'}</span></div><p>{stop.explanation}</p><div className="stop-bottom"><span><Clock3 size={14}/>{stop.dwell_minutes} min to explore</span><span><Leaf size={14}/>{stop.rest_minutes} min to rest</span></div></div></article>)}</div>
 <div className="finish-point"><span className="icon-circle"><Check size={17}/></span><div><b>{clock(plan.finish_min)} · A day well spent</b><p>Your plan ends at the final visit. A return transfer is not included.</p></div></div>
 {plan.skipped_place_ids.length>0&&<div className="card skipped"><h3>Something for another day</h3><p>{plan.skipped_place_ids.map(id=>id.replaceAll('-',' ')).join(', ')} did not fit this plan. Keeping a comfortable day comes first.</p></div>}
 <div className="disruption-card"><div className="icon-circle"><RefreshCw size={20}/></div><div><h3>A little change needn’t change everything.</h3><p>Explore what a delay could mean for your remaining visits.</p></div><button className="button secondary" onClick={onDelay}>Explore a delay<ArrowUpRight size={16}/></button></div></section>
 <aside className="journey-aside"><RouteMap plan={plan}/><div className="card budget-card"><span className="eyebrow">GROUP TRANSPORT ESTIMATE</span><div className="big-price">{money(plan.total_cost_inr)}</div><p>For {plan.request.party_size} travelers · {plan.total_travel_minutes} min on the move</p><div className="budget-bar"><span style={{width:`${Math.min(100,plan.total_cost_inr/plan.request.budget_inr*100)}%`}}/></div><div className="budget-meta"><span>Your budget</span><b>{money(plan.request.budget_inr)}</b></div><div className="budget-meta"><span>Room in your budget</span><b>{money(plan.request.budget_inr-plan.total_cost_inr)}</b></div><small>Estimated transport only. Meals, entry fees and tickets are extra. No return transfer is included.</small></div><div className="card share-card"><h3>Carry the day with you.</h3><button className="text-button" onClick={()=>window.print()}><Printer size={15}/>Print itinerary</button><button className="text-button" onClick={onExport}><Download size={15}/>Export journey backup</button><p>Keep an offline copy before you leave.</p></div></aside></div><div className="data-note"><MapPin size={15}/><p>{plan.disclaimer}</p></div></>;
}
function CalendarLabel({date}:{date:string}){return <><Clock3 size={15}/>{tripDate(date)}</>}
