import {ArrowRight,CalendarDays,Clock3,Heart,IndianRupee,Leaf,MapPin,Users} from 'lucide-react';
import type {Catalog,Language,Preferences} from '../types';
import {clock} from '../types';
import {t} from '../i18n';
export function Planner({catalog,preferences,setPreferences,onSubmit,busy,language}:{catalog:Catalog|null;preferences:Preferences;setPreferences:(p:Preferences)=>void;onSubmit:()=>void;busy:boolean;language:Language}){
 const change=<K extends keyof Preferences>(key:K,value:Preferences[K])=>setPreferences({...preferences,[key]:value});
 const pick=(id:string,kind:string)=>setPreferences({...preferences,required_place_ids:[...preferences.required_place_ids.filter(x=>x!==id),...(kind==='required'?[id]:[])],optional_place_ids:[...preferences.optional_place_ids.filter(x=>x!==id),...(kind==='optional'?[id]:[])]});
 return <><div className="page-intro"><span className="eyebrow">A DAY BUILT AROUND YOU</span><h1>Make room for what matters.</h1><p>A few thoughtful choices. A day with space to breathe.</p></div><form className="planner-layout" onSubmit={event=>{event.preventDefault();onSubmit()}}>
 <aside className="preferences card"><div className="section-title"><span className="icon-circle"><Heart size={17}/></span><h2>Your journey</h2></div><label className="field"><span><MapPin size={14}/> Starting point</span><select aria-label="Starting point" value="madurai-station" disabled><option>Madurai Junction</option></select><small>One-day journeys in and around Madurai.</small></label>
 <label className="field"><span><CalendarDays size={14}/> Journey date</span><input aria-label="Journey date" type="date" required value={preferences.date} onChange={e=>change('date',e.target.value)}/></label>
 <div className="field-pair"><label className="field"><span><Clock3 size={14}/> Departure time</span><input aria-label="Departure time" type="time" required value={preferences.start_time} onChange={e=>change('start_time',e.target.value)}/></label><label className="field"><span>Finish by</span><input aria-label="Finish by" type="time" required value={preferences.end_time} onChange={e=>change('end_time',e.target.value)}/></label></div>
 <div className="field-pair"><label className="field"><span><Users size={14}/> Travelers</span><input aria-label="Travelers" type="number" required min="1" max="20" value={preferences.party_size} onChange={e=>change('party_size',Number(e.target.value))}/></label><label className="field"><span><IndianRupee size={14}/> Group budget</span><input aria-label="Group transport budget" type="number" required min="1" max="100000" value={preferences.budget_inr} onChange={e=>change('budget_inr',Number(e.target.value))}/></label></div><p className="field-note">Transport for the whole group. Meals, entry fees and tickets are extra.</p>
 <fieldset className="pace-group"><legend><Leaf size={14}/> {t(language).pace}</legend>{(['relaxed','standard'] as const).map(p=><label key={p} className={`pace-option ${preferences.pace===p?'selected':''}`}><input type="radio" name="pace" value={p} checked={preferences.pace===p} onChange={()=>change('pace',p)}/><span><b>{p==='relaxed'?t(language).relaxed:t(language).standard}</b><small>{p==='relaxed'?'Longer visits · 20-minute pauses':'Classic visits · 10-minute pauses'}</small></span></label>)}</fieldset>
 <label className="field"><span>How you like to travel</span><select aria-label="Transport preference" value={preferences.transport} onChange={e=>change('transport',e.target.value as Preferences['transport'])}><option value="balanced">A thoughtful mix of cab & bus</option><option value="cab">Cab transfers</option><option value="bus">Bus transfers</option></select></label>
 <button className="button primary full" disabled={busy||!catalog}>{busy?'Arranging your day…':t(language).build}<ArrowRight size={17}/></button>{busy&&<p className="field-note" role="status">Allow a little time for the planner to wake up and check your choices.</p>}
 </aside><section className="visit-choices"><div className="section-heading"><div><h2>What brings you here?</h2><p>Keep your must-see moments. Let the rest unfold.</p></div><span className="muted-chip">{preferences.required_place_ids.length} must-see</span></div>
 {!catalog?<div className="card empty-state"><MapPin/><h3>Connecting to your journey planner</h3><p>The destination list will appear when the planning service is available.</p></div>:catalog.places.map((place,index)=><article className="place-card card" key={place.id}><div className={`place-art art-${place.category}`} aria-hidden="true"><span>{String(index+1).padStart(2,'0')}</span>{place.category==='temple'?<span className="temple-glyph">♜</span>:place.category==='heritage'?<span className="temple-glyph">♖</span>:<Leaf size={35}/>}</div><div className="place-copy"><span className="eyebrow">{place.category}</span><h3>{language==='ta'?place.tamil_name:place.name}</h3><p>{place.description}</p><div className="place-meta"><Clock3 size={12}/>{place.windows.map(([a,b])=>`${clock(a)}–${clock(b)}`).join(' · ')}<span>Example hours</span></div></div><label className="priority"><span className="sr-only">Priority for {place.name}</span><select aria-label={`Priority for ${place.name}`} value={preferences.required_place_ids.includes(place.id)?'required':preferences.optional_place_ids.includes(place.id)?'optional':'skip'} onChange={e=>pick(place.id,e.target.value)}><option value="required">{t(language).must}</option><option value="optional">{t(language).optional}</option><option value="skip">{t(language).skip}</option></select></label></article>)}
 <div className="gentle-note"><Heart size={18}/><p>More places don’t always make a better journey. Leave room for conversations, a cup of tea, and a moment that stays with you.</p></div></section></form></>;
}
