/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v2_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/places/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v2_places_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/places/{place_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Place */
        get: operations["place_api_v2_places__place_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v2_me_get"];
        put?: never;
        post?: never;
        /** Delete Account Data */
        delete: operations["delete_account_data_api_v2_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips_api_v2_trips_get"];
        put?: never;
        /** Create Trip */
        post: operations["create_trip_api_v2_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["get_trip_api_v2_trips__trip_id__get"];
        put?: never;
        post?: never;
        /** Delete Trip */
        delete: operations["delete_trip_api_v2_trips__trip_id__delete"];
        options?: never;
        head?: never;
        /** Change Trip */
        patch: operations["change_trip_api_v2_trips__trip_id__patch"];
        trace?: never;
    };
    "/api/v2/trips/{trip_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Trip */
        get: operations["export_trip_api_v2_trips__trip_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/imports/legacy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Legacy */
        post: operations["import_legacy_api_v2_imports_legacy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Catalog */
        get: operations["get_catalog_api_v1_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_v1_plans_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/replan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replan Preview */
        post: operations["replan_preview_api_v1_plans_replan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LegacyRequest */
        LegacyRequest: {
            /** Original */
            original: string;
        };
        /** PlaceSearchResult */
        PlaceSearchResult: {
            /** Places */
            places: components["schemas"]["ResolvedPlace"][];
            /** Request Id */
            request_id: string;
            /** Source */
            source: string;
            /**
             * Partial
             * @default false
             */
            partial: boolean;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Message */
            message?: string | null;
        };
        /** PlanRequest */
        PlanRequest: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Start Time
             * @default 08:00
             */
            start_time: string;
            /**
             * End Time
             * @default 19:00
             */
            end_time: string;
            /**
             * Budget Inr
             * @default 3500
             */
            budget_inr: number;
            /**
             * Party Size
             * @default 3
             */
            party_size: number;
            /** Required Place Ids */
            required_place_ids?: string[];
            /** Optional Place Ids */
            optional_place_ids?: string[];
            /**
             * Pace
             * @default relaxed
             * @enum {string}
             */
            pace: "standard" | "relaxed";
            /**
             * Transport
             * @default balanced
             * @enum {string}
             */
            transport: "balanced" | "bus" | "cab";
            /**
             * Max Stops
             * @default 6
             */
            max_stops: number;
        };
        /** PlanResult */
        PlanResult: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Feasible */
            feasible: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "optimal" | "feasible" | "infeasible" | "timeout";
            request: components["schemas"]["PlanRequest"];
            /** Stops */
            stops?: components["schemas"]["Stop"][];
            /** Skipped Place Ids */
            skipped_place_ids?: string[];
            /**
             * Total Cost Inr
             * @default 0
             */
            total_cost_inr: number;
            /**
             * Total Travel Minutes
             * @default 0
             */
            total_travel_minutes: number;
            /**
             * Finish Min
             * @default 0
             */
            finish_min: number;
            /** Suggestions */
            suggestions?: string[];
            /** Disclaimer */
            disclaimer: string;
            /** Dataset Version */
            dataset_version: string;
            /**
             * Completed Count
             * @default 0
             */
            completed_count: number;
            /**
             * Progress Min
             * @default 0
             */
            progress_min: number;
            /**
             * Signature
             * @default
             */
            signature: string;
        };
        /** ReplanRequest */
        ReplanRequest: {
            original_plan: components["schemas"]["PlanResult"];
            /**
             * Completed Count
             * @default 0
             */
            completed_count: number;
            /**
             * Delay Minutes
             * @default 45
             */
            delay_minutes: number;
        };
        /** ResolvedPlace */
        ResolvedPlace: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Provider */
            provider: string;
            /** Source Id */
            source_id: string;
            /** Name */
            name: string;
            /** Local Name */
            local_name?: string | null;
            /** Address */
            address?: string | null;
            /** Country */
            country?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Region */
            region?: string | null;
            /** Longitude */
            longitude: number;
            /** Latitude */
            latitude: number;
            /** Timezone */
            timezone?: string | null;
            /**
             * Kind
             * @default place
             */
            kind: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Observed At */
            observed_at?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * License
             * @default ODbL-1.0
             */
            license: string;
            /**
             * Attribution
             * @default © OpenStreetMap contributors · Powered by Geoapify
             */
            attribution: string;
        };
        /** Stop */
        Stop: {
            /** Place Id */
            place_id: string;
            /** Name */
            name: string;
            /** Tamil Name */
            tamil_name: string;
            /** Arrival Min */
            arrival_min: number;
            /** Departure Min */
            departure_min: number;
            /** Dwell Minutes */
            dwell_minutes: number;
            /** Rest Minutes */
            rest_minutes: number;
            /** Travel Minutes */
            travel_minutes: number;
            /** Wait Minutes */
            wait_minutes: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "bus" | "cab";
            /** Cost Inr */
            cost_inr: number;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Explanation */
            explanation: string;
        };
        /** TripChange */
        TripChange: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "update_metadata" | "add_item" | "move_item" | "update_item" | "remove_item";
            /** Place Id */
            place_id?: string | null;
            /** Item Id */
            item_id?: string | null;
            /** Day Index */
            day_index?: number | null;
            /** Position */
            position?: number | null;
            /** Notes */
            notes?: string | null;
            metadata?: components["schemas"]["TripCreate"] | null;
        };
        /** TripCreate */
        TripCreate: {
            /** Title */
            title: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Timezone
             * @default Asia/Kolkata
             */
            timezone: string;
            /**
             * Currency
             * @default INR
             */
            currency: string;
        };
        /** TripDocument */
        TripDocument: {
            /** Title */
            title: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Timezone
             * @default Asia/Kolkata
             */
            timezone: string;
            /**
             * Currency
             * @default INR
             */
            currency: string;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Items */
            items?: components["schemas"]["TripItem"][];
            /**
             * Origin
             * @default user
             */
            origin: string;
        };
        /** TripItem */
        TripItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Day Index */
            day_index: number;
            /** Position */
            position: number;
            place: components["schemas"]["ResolvedPlace"];
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capabilities_api_v2_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    search_api_v2_places_search_get: {
        parameters: {
            query: {
                q: string;
                language?: string;
                country?: string | null;
                limit?: number;
                source?: "cities" | "places";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceSearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    place_api_v2_places__place_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedPlace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v2_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    delete_account_data_api_v2_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_trips_api_v2_trips_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_trip_api_v2_trips_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip_api_v2_trips__trip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trip_api_v2_trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_trip_api_v2_trips__trip_id__patch: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "If-Match"?: string | null;
            };
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_trip_api_v2_trips__trip_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_legacy_api_v2_imports_legacy_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegacyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_catalog_api_v1_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    preview_api_v1_plans_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replan_preview_api_v1_plans_replan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
