import {useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,Bookmark,Check,Clock3,Compass,Flower2,Heart,Leaf,MapPin,Menu,Plus,RefreshCw,Route,Trash2,Upload,X} from 'lucide-react';
import type {Catalog,Language,Plan,Preferences,SavedJourney} from './types';
import {clock,money,tripDate} from './types';
import {fetchCatalog,preview,delayPlan} from './api';
import {exportPlan,importPlan,loadSaved,persistSaved} from './storage';
import {t} from './i18n';
import {TempleArt} from './components/TempleArt';
import {Planner} from './components/Planner';
import {Itinerary} from './components/Itinerary';
import {useModal} from './components/useModal';

type Page='discover'|'planner'|'journey'|'saved';
const initial:Preferences={date:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),start_time:'08:00',end_time:'19:00',budget_inr:3500,party_size:3,required_place_ids:['meenakshi','palace'],optional_place_ids:['gandhi','teppakulam'],pace:'relaxed',transport:'balanced',max_stops:6};

export default function App(){
 const [page,setPage]=useState<Page>('discover'),[catalog,setCatalog]=useState<Catalog|null>(null),[preferences,setPreferences]=useState(initial),[plan,setPlan]=useState<Plan|null>(null),[saved,setSaved]=useState<SavedJourney[]>(loadSaved),[language,setLanguage]=useState<Language>('en'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[menu,setMenu]=useState(false),[catalogError,setCatalogError]=useState('');
 const [delayOpen,setDelayOpen]=useState(false),[completed,setCompleted]=useState(1),[delay,setDelay]=useState(45),[alternative,setAlternative]=useState<Plan|null>(null);
 const modalRef=useModal(delayOpen,busy,()=>{setDelayOpen(false);setError('')});
 const connect=()=>{setCatalogError('');fetchCatalog().then(setCatalog).catch(e=>setCatalogError(e.message))};
 useEffect(()=>{connect()},[]);
 useEffect(()=>{document.documentElement.lang=language;},[language]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(timer)},[notice]);
 const go=(next:Page)=>{setPage(next);setMenu(false);setError('');setAlternative(null);setDelayOpen(false);window.scrollTo({top:0,behavior:'smooth'})};
 const build=async()=>{setError('');setBusy(true);try{const result=await preview(preferences);setPlan(result);if(result.feasible)go('journey');else setError(result.status==='timeout'?'The planner needs another moment. Try fewer optional visits.':`These choices don’t fit a complete day. ${result.suggestions.join(' ')}`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const save=(value:Plan)=>{if(saved.some(s=>s.plan.signature===value.signature)){setNotice('This journey is already saved in this browser.');return;}const next=[{id:crypto.randomUUID(),saved_at:new Date().toISOString(),plan:value},...saved].slice(0,50);try{persistSaved(next);setSaved(next);setNotice('Journey saved in this browser. Export a backup to keep it elsewhere.')}catch(e){setError((e as Error).message)}};
 const remove=(id:string)=>{const next=saved.filter(s=>s.id!==id);try{persistSaved(next);setSaved(next);setNotice('Journey removed from this browser.')}catch(e){setError((e as Error).message)}};
 const open=(value:Plan)=>{setPlan(value);setPreferences(value.request);go('journey')};
 const importFile=async(file:File|undefined)=>{if(!file)return;setError('');try{if(file.size>65536)throw new Error('Choose a valid Payanam journey file smaller than 64 KB.');const result=importPlan(await file.text());if(!result.feasible)throw new Error('Choose a valid Payanam journey with a feasible itinerary.');save(result);}catch(e){setError((e as Error).message)}};
 const explore=()=>{setCompleted(plan?Math.max(plan.completed_count,plan.stops.length>1?1:0):0);setAlternative(null);setError('');setDelayOpen(true)};
 const compare=async()=>{if(!plan)return;setError('');setBusy(true);try{setAlternative(await delayPlan(plan,completed,delay))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <div className="app-shell"><a className="skip-link" href="#main">Skip to content</a><aside className={`sidebar ${menu?'is-open':''}`}><button className="brand" onClick={()=>go('discover')} aria-label="Payanam home"><span className="brand-mark"><Route size={27}/></span><span>payanam<small>பயணம் · the journey</small></span></button><div className="nav-label">YOUR JOURNEY SPACE</div><nav aria-label="Main navigation">{([['discover',Compass,t(language).home],['planner',MapPin,t(language).planner],['saved',Bookmark,t(language).saved]] as const).map(([key,Icon,label])=><button key={key} className={`nav-item ${page===key||page==='journey'&&key==='planner'?'active':''}`} onClick={()=>go(key)}><Icon size={19}/>{label}{key==='saved'&&saved.length>0&&<span className="count">{saved.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-quote"><Flower2 size={24}/><p>The journey matters.<br/>So do the people<br/>you share it with.</p><span>A LITTLE LESS HURRY.</span></div><div className="local-tag"><span className="green-dot"/>Rooted in Tamil Nadu</div></div></aside>
 <div className="main-shell"><header className="topbar"><div className="topbar-left"><button className="menu-button" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}><Menu size={21}/></button><span className="breadcrumb">Your journey space<span>/</span><b>{page==='discover'?'Discover':page==='saved'?'Saved journeys':page==='journey'?'Your itinerary':'Plan a journey'}</b></span></div><div className="topbar-right"><span className="region-pill"><MapPin size={13}/>Madurai, Tamil Nadu</span><button className="language-toggle" aria-label="Switch Tamil place names and navigation" title="Tamil place names and core navigation" onClick={()=>setLanguage(language==='en'?'ta':'en')}><span className={language==='en'?'current':''}>EN</span><span className={language==='ta'?'current':''}>தமிழ்</span></button><div className="avatar" aria-label="Your personal journey space">P</div></div></header>
 <main id="main"><div className="content">{error&&<div className="error-banner" role="alert"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={17}/></button></div>}{notice&&<div className="notice-banner" role="status"><Check size={17}/>{notice}</div>}{catalogError&&page==='planner'&&<div className="error-banner" role="alert"><span>{catalogError}</span><button className="text-button" onClick={connect}>Try again<RefreshCw size={15}/></button></div>}
 {page==='discover'&&<><div className="welcome-line"><span className="eyebrow">THOUGHTFUL JOURNEYS, CLOSER TO HOME</span><span className="edition">THE MADURAI EDITION · 01</span></div><section className="hero"><div className="hero-copy"><span className="hero-kicker"><span className="little-line"/>A LITTLE MORE JOURNEY. A LITTLE LESS WORRY.</span><h1>Go where your<br/>heart takes you.<br/><em>We’ll mind the day.</em></h1><p>Meaningful places. A pace that feels right.<br/>A thoughtful plan for you and the people<br className="desktop-break"/> you love traveling with.</p><button className="button primary" onClick={()=>go('planner')}>{t(language).plan}<ArrowRight size={17}/></button><div className="hero-footnote"><Leaf size={14}/>Made for moments, not just miles.</div></div><div className="hero-visual"><TempleArt/><div className="location-caption"><span>9.9195° N · 78.1193° E</span><b>Madurai, where every day has a story.</b></div></div></section>
 <section className="values-strip"><div><span className="icon-circle"><Heart size={19}/></span><span><b>What matters to you</b><small>Your must-see moments come first.</small></span></div><div><span className="icon-circle"><Leaf size={19}/></span><span><b>Space to slow down</b><small>Real time to visit, rest, and just be.</small></span></div><div><span className="icon-circle"><RefreshCw size={18}/></span><span><b>A day that can adapt</b><small>Thoughtful alternatives when plans change.</small></span></div></section>
 <section className="inspiration"><div className="section-heading"><div><span className="eyebrow">FIND YOUR KIND OF DAY</span><h2>Every journey begins with a feeling.</h2></div><button className="text-button" onClick={()=>go('planner')}>Make it your own<ArrowUpRight size={16}/></button></div><div className="inspiration-grid">{[{title:'Sacred & slow',tag:'A MOMENT OF CONNECTION',icon:Flower2,className:'sacred',description:'Temple visits, quiet pauses, and a day with your family at its heart.',required:['meenakshi','alagar'],optional:['pazhamudircholai'],pace:'relaxed'},{title:'A city with a story',tag:'FOLLOW YOUR CURIOSITY',icon:Compass,className:'heritage',description:'A palace, a museum, and a little more of Madurai’s many layers.',required:['palace','gandhi'],optional:['teppakulam'],pace:'standard'},{title:'A little of everything',tag:'LET THE DAY UNFOLD',icon:Leaf,className:'mixed',description:'One meaningful visit, a little exploring, and room to breathe.',required:['meenakshi','palace'],optional:['gandhi','teppakulam'],pace:'relaxed'}].map((idea,index)=><button className={`inspiration-card ${idea.className}`} key={idea.title} onClick={()=>{setPreferences({...preferences,required_place_ids:idea.required,optional_place_ids:idea.optional,pace:idea.pace as Preferences['pace']});go('planner')}}><div className="idea-art"><idea.icon size={40} strokeWidth={1.1}/><span>0{index+1}</span><div className="art-orbit"/></div><div className="idea-content"><span className="eyebrow">{idea.tag}</span><h3>{idea.title}</h3><p>{idea.description}</p><span className="idea-action">Explore this day<ArrowRight size={16}/></span></div></button>)}</div></section><div className="promise-note"><Flower2 size={20}/><p>Travel with confidence. Keep the moments that matter.</p><span>THE PAYANAM PROMISE</span></div><div className="data-note"><MapPin size={15}/><p>This is a planning preview using illustrative Madurai data. Confirm hours and fares locally. No tickets or transport are booked.</p></div></>}
 {page==='planner'&&<Planner catalog={catalog} preferences={preferences} setPreferences={setPreferences} onSubmit={build} busy={busy} language={language}/>}
 {page==='journey'&&plan&&<Itinerary plan={plan} language={language} saved={saved.some(s=>s.plan.signature===plan.signature)} onSave={()=>save(plan)} onEdit={()=>go('planner')} onDelay={explore} onExport={()=>exportPlan(plan)}/>}
 {page==='saved'&&<><div className="page-intro itinerary-intro"><div><span className="eyebrow">A JOURNEY TO RETURN TO</span><h1>Your days, kept close.</h1><p>Saved in this browser. Export a backup to take them elsewhere.</p></div><label className="button secondary import-button"><Upload size={16}/>Import journey<input type="file" aria-label="Import journey" accept="application/json,.json" onChange={e=>{void importFile(e.target.files?.[0]);e.target.value=''}}/></label></div>{saved.length===0?<div className="card empty-state"><Bookmark size={36}/><h2>The next memory starts here.</h2><p>Save an itinerary and it will be waiting here when you return.</p><button className="button primary" onClick={()=>go('planner')}>Plan a journey<Plus size={17}/></button></div>:<div className="saved-grid">{saved.map(item=><article className="card saved-card" key={item.id}><div className="saved-card-top"><span className="icon-circle"><Route size={20}/></span><span className="muted-chip">{item.plan.stops.length} visits</span></div><h2>A day in Madurai</h2><p>{tripDate(item.plan.request.date)} · {item.plan.request.party_size} travelers</p><div className="saved-place-list">{item.plan.stops.map(s=><span key={s.place_id}>{language==='ta'?s.tamil_name:s.name}</span>)}</div><div className="saved-bottom"><b>{money(item.plan.total_cost_inr)}</b><button className="text-button" onClick={()=>open(item.plan)}>Open itinerary<ArrowRight size={15}/></button><button className="icon-button" aria-label={`Delete journey saved ${item.saved_at}`} onClick={()=>remove(item.id)}><Trash2 size={15}/></button></div></article>)}</div>}</>}
 </div><footer><span>payanam<span className="footer-dot">·</span>Journeys with a little more soul.</span><span>Made with care for Tamil Nadu.</span></footer></main></div>
 {delayOpen&&plan&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy){setDelayOpen(false);setError('')}}}><section ref={modalRef} className="modal card" role="dialog" aria-modal="true" aria-labelledby="delay-title"><button className="modal-close icon-button" aria-label="Close delay comparison" onClick={()=>{setDelayOpen(false);setError('')}} disabled={busy}><X size={20}/></button><span className="icon-circle"><RefreshCw size={22}/></span><span className="eyebrow">A SIMULATION, BEFORE YOU DECIDE</span><h2 id="delay-title">{alternative?'A change of plan. The same purpose.':'Let’s leave room for a change.'}</h2><p>See how a delay affects the visits still ahead. Nothing is changed until you choose.</p>{error&&<div className="error-banner" role="alert">{error}</div>}
 {!alternative?<><label className="field"><span>How far have you traveled?</span><select aria-label="Completed visits" value={completed} onChange={e=>setCompleted(Number(e.target.value))}>{Array.from({length:plan.stops.length-plan.completed_count},(_,offset)=>{const i=offset+plan.completed_count;return <option key={i} value={i}>{i===0?'Before leaving Madurai Junction':`After ${plan.stops[i-1].name}`}</option>})}</select></label><label className="field"><span>How long is the delay?</span><select aria-label="Delay duration" value={delay} onChange={e=>setDelay(Number(e.target.value))}>{[15,30,45,60,90,120].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label><button className="button primary full" disabled={busy} onClick={compare}>{busy?'Considering the alternatives…':'Compare alternatives'}<ArrowRight size={17}/></button></>:<>{alternative.feasible?<><div className="comparison-grid"><div><span className="eyebrow">YOUR ORIGINAL DAY</span><b>{clock(plan.finish_min)}</b><small>{plan.stops.length} visits · {money(plan.total_cost_inr)}</small></div><div className="revised"><span className="eyebrow">WITH A {delay}-MINUTE DELAY</span><b>{clock(alternative.finish_min)}</b><small>{alternative.stops.length} visits · {money(alternative.total_cost_inr)}</small></div></div><p className="comparison-note">{completed} completed {completed===1?'visit stays':'visits stay'} exactly as planned. Group transport changes by {money(alternative.total_cost_inr-plan.total_cost_inr)}.</p><div className="mini-timeline">{alternative.stops.map((s,i)=><div key={s.place_id}><span>{i<completed?<Check size={12}/>:clock(s.arrival_min)}</span><b>{s.name}</b></div>)}</div><button className="button primary full" onClick={()=>{setPlan(alternative);setDelayOpen(false);setAlternative(null);setError('');setNotice('Your revised day is ready. Save it to keep this new version.')}}>Use revised plan<Check size={16}/></button></>:<div className="infeasible-note"><h3>The full day no longer fits.</h3>{alternative.suggestions.map(s=><p key={s}>{s}</p>)}<p>Your original itinerary is unchanged.</p></div>}<button className="button secondary full" onClick={()=>{setDelayOpen(false);setAlternative(null);setError('')}}>Keep original</button><button className="text-button" onClick={()=>setAlternative(null)}>Try a different delay</button></>}
 <small className="modal-footnote">Illustrative transport estimates. No reservations are changed.</small></section></div>}
 </div>
}
